export const MAGENTO2 = "magento2";
export const SHIPMENT_ACTION_ORDER = "SHIPMENT_ACTION_ORDER";
export const CANCEL_ACTION_ORDER = "CANCEL_ACTION_ORDER";
export const REFUND_ACTION_ORDER = "REFUND_ACTION_ORDER";
export const ADD_NOTE_ACTION_ORDER = "ADD_NOTE_ACTION_ORDER";