FROM node:12.13-alpine As development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN rm -rf /usr/src/app/apps/category
RUN rm -rf /usr/src/app/apps/coreapi
RUN rm -rf /usr/src/app/apps/cashier
RUN rm -rf /usr/src/app/apps/product

## Add the wait script to the image
RUN chmod +x /usr/src/app/scripts/wait-for.sh

CMD ["npm", "run" ,"start:dev", "graphql"]

